version: "3.5"

services:
  postgres:
    container_name: postgres
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: defaultdb
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  cache:
    container_name: redis-caching
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
